--Holds applicant information
CREATE TABLE IF NOT EXISTS APPLICANT_DETAILS(
APPLICANT_ID NUMERIC PRIMARY KEY, 
FIRST_NAME VARCHAR DEFAULT NOT NULL, 
LAST_NAME VARCHAR DEFAULT NOT NULL, 
SKILL VARCHAR DEFAULT NOT NULL,
YEARS_OF_EXPERIENCE NUMERIC,
EMAIL VARCHAR DEFAULT NOT NULL,
PHONE_NUMBER VARCHAR DEFAULT NOT NULL,
PRIMARY KEY (APPLICANT_ID));

-- Holds recruiter information
CREATE TABLE IF NOT EXISTS INTERVIEWER_DETAILS(
INTERVIEWER_ID NUMERIC PRIMARY KEY, 
FIRST_NAME VARCHAR DEFAULT NOT NULL, 
LAST_NAME VARCHAR DEFAULT NOT NULL, 
SKILL VARCHAR DEFAULT NOT NULL,
YEARS_OF_EXPERIENCE NUMERIC,
DESIGNATION VARCHAR DEFAULT NOT NULL,
PRIMARY KEY (INTERVIEWER_ID));

--Holds Application details
CREATE TABLE IF NOT EXISTS APPLICATION_DETAILS(
APPLICATION_ID NUMERIC PRIMARY KEY, 
IS_REJECTED BOOLEAN DEFAULT FALSE,
NOTE VARCHAR DEFAULT NULL,
ROUND NUMERIC DEFAULT NULL,
APPLICANT_ID VARCHAR,
INTERVIEWER_ID VARCHAR,
JOB_ID VARCHAR,
FOREIGN KEY (APPLICANT_ID) REFERENCES APPLICANT_DETAILS(APPLICANT_ID),
FOREIGN KEY (INTERVIEWER_ID) REFERENCES RECRUITER_DETAILS(INTERVIEWER_ID),
FOREIGN KEY (JOB_ID) REFERENCES JOB_DETAILS(JOB_ID),
PRIMARY KEY (APPLICATION_ID));

--Available job details
CREATE TABLE IF NOT EXISTS JOB_DETAILS(
JOB_ID NUMERIC PRIMARY KEY, 
DESCRIPTION VARCHAR DEFAULT NOT NULL, 
SKILLS_REQUIRED VARCHAR DEFAULT NOT NULL,
DESIGNATION VARCHAR DEFAULT NOT NULL,
YEARS_OF_EXPERIENCE NUMERIC DEFAULT NOT NULL,
PRIMARY KEY (JOB_ID));

insert into JOB_DETAILS(JOB_ID, DESCRIPTION, SKILLS_REQUIRED, DESIGNATION, YEARS_OF_EXPERIENCE) values (1, 'Test job detail 1', 'Spring Boot', 'Consultant', 4);
insert into JOB_DETAILS(JOB_ID, DESCRIPTION, SKILLS_REQUIRED, DESIGNATION, YEARS_OF_EXPERIENCE) values (2, 'Test job detail 2', 'Spring Boot', 'BTA', 1);
insert into JOB_DETAILS(JOB_ID, DESCRIPTION, SKILLS_REQUIRED, DESIGNATION, YEARS_OF_EXPERIENCE) values (3, 'Test job detail 3', 'Spring Boot', 'Consultant', 6);
--insert into EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID) values (2, 'Jatin', 'Dubey', 'Consulting');